### ISSUE TITLE
Crash of the content blocker

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#182]
```
05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime: FATAL EXCEPTION: main05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime: Process: com.adguard.android.contentblocker, PID: 1479605-02 15:15:02.018 10145 14796 14796 E AndroidRuntime: android.content.res.Resources$NotFoundException: Resource ID #0x005-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:228)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.content.res.Resources.getColor(Resources.java:976)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.content.res.Resources.getColor(Resources.java:952)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.android.internal.app.AlertController.setupButtons(AlertController.java:844)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.android.internal.app.AlertController.setupView(AlertController.java:565)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.android.internal.app.AlertController.installContent(AlertController.java:282)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.AlertDialog.onCreate(AlertDialog.java:440)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.ProgressDialog.onCreate(ProgressDialog.java:330)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.Dialog.dispatchOnCreate(Dialog.java:549)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.Dialog.show(Dialog.java:390)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.ProgressDialog.show(ProgressDialog.java:220)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.ProgressDialog.show(ProgressDialog.java:194)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.adguard.android.contentblocker.ui.utils.ProgressDialogUtils.showProgressDialog(ProgressDialogUtils.java:42)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.adguard.android.contentblocker.service.FilterServiceImpl.checkFiltersUpdates(FilterServiceImpl.java:141)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.adguard.android.contentblocker.ui.MainActivity.onClick(MainActivity.java:357)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.view.View.performClick(View.java:7315)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.view.View.performClickInternal(View.java:7281)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.view.View.access$3200(View.java:846)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.view.View$PerformClick.run(View.java:27747)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:873)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:6992)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)05-02 15:15:02.018 10145 14796 14796 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by ameshkov** [comment]
Might be happening with the version that's in the Galaxy store only

**Comment by artemiv4nov** [comment]
Can't reproduce on latest version
