### ISSUE TITLE
App crash on Android v4.4.2

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#19]
```
06-07 20:24:16.441 E/AndroidRuntime(23810): FATAL EXCEPTION: main

06-07 20:24:16.441 E/AndroidRuntime(23810): Process: com.adguard.android.contentblocker, PID: 23810

06-07 20:24:16.441 E/AndroidRuntime(23810): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard.android.contentblocker/com.adguard.android.contentblocker.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2334)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread.access$900(ActivityThread.java:169)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.os.Handler.dispatchMessage(Handler.java:102)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.os.Looper.loop(Looper.java:146)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread.main(ActivityThread.java:5487)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at java.lang.reflect.Method.invokeNative(Native Method)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at java.lang.reflect.Method.invoke(Method.java:515)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at dalvik.system.NativeStart.main(Native Method)

06-07 20:24:16.441 E/AndroidRuntime(23810): Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.support.v7.app.AppCompatDelegateImplV7.setSupportActionBar(AppCompatDelegateImplV7.java:197)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.support.v7.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:126)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at com.adguard.android.contentblocker.MainActivity.onCreate(MainActivity.java:80)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.Activity.performCreate(Activity.java:5451)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)

06-07 20:24:16.441 E/AndroidRuntime(23810): 	... 11 more
```

**Comment by Revertron** [comment]
Already fixed.
