### ISSUE TITLE
Crash when user tries to start YaBrowser

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#29]
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.yandex.browser/com.yandex.browser.YandexBrowserMainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1545)
	at android.app.Activity.startActivityForResult(Activity.java:4283)
	at android.app.Activity.startActivityForResult(Activity.java:4230)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
	at android.app.Activity.startActivity(Activity.java:4567)
	at android.app.Activity.startActivity(Activity.java:4535)
	at com.adguard.android.commons.BrowserUtils.startBrowser(BrowserUtils.java:233)
	at com.adguard.android.commons.BrowserUtils.startYandexBrowser(BrowserUtils.java:220)
	at com.adguard.android.contentblocker.MainActivity$6.onClick(MainActivity.java:197)
	at android.view.View.performClick(View.java:5697)
	at android.widget.TextView.performClick(TextView.java:10826)
	at android.view.View$PerformClick.run(View.java:22526)
	at android.os.Handler.handleCallback(Handler.java:739)
```

**Comment by nkartyshov** [comment]
done
