### ISSUE TITLE
Crash in ApplyAndRefreshTask

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#35]
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{c3f36e5 V.E...... R.....ID 0,0-1069,406} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:377)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:122)
	at android.app.Dialog.dismissDialog(Dialog.java:546)
	at android.app.Dialog.dismiss(Dialog.java:529)
	at com.adguard.android.contentblocker.ApplyAndRefreshTask.onPostExecute(ApplyAndRefreshTask.java:36)
	at com.adguard.android.contentblocker.ApplyAndRefreshTask.onPostExecute(ApplyAndRefreshTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:651)
	at android.os.AsyncTask.access$500(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by nkartyshov** [comment]
fixed
