### ISSUE TITLE
Binary XML file line #23: You must supply a layout_width attribute

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/ContentBlocker#36]
`java.lang.RuntimeException: Binary XML file line #23: You must supply a layout_width attribute.
	at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
	at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5844)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:5986)
	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1854)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1766)
	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:62)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:759)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
	at com.adguard.android.commons.BrowserUtils.showBrowserInstallDialog(BrowserUtils.java:183)
	at com.adguard.android.contentblocker.onboarding.OnboardingActivity.onClick(OnboardingActivity.java:166)
	at android.view.View.performClick(View.java:4452)
	at android.widget.Button.performClick(Button.java:148)
	at android.view.View$PerformClick.run(View.java:18428)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5365)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by nkartyshov** [comment]
fixed
