### ISSUE TITLE
Unable to get provider com.adguard.android.contentblocker.FiltersContentProvider

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#38]
```
java.lang.RuntimeException: Unable to get provider com.adguard.android.contentblocker.FiltersContentProvider: java.lang.ClassNotFoundException: Didn't find class "com.adguard.android.contentblocker.FiltersContentProvider" on path: DexPathList[[zip file "/mnt/asec/com.adguard.android.contentblocker-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.adguard.android.contentblocker-1/lib, /vendor/lib, /system/lib]]
	at android.app.ActivityThread.installProvider(ActivityThread.java:5018)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4589)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4522)
	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.adguard.android.contentblocker.FiltersContentProvider" on path: DexPathList[[zip file "/mnt/asec/com.adguard.android.contentblocker-1/pkg.apk"],nativeLibraryDirectories=[/mnt/asec/com.adguard.android.contentblocker-1/lib, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5003)
	... 12 more
	Suppressed: java.io.IOException: unable to open DEX file
		at dalvik.system.DexFile.openDexFileNative(Native Method)
		at dalvik.system.DexFile.openDexFile(DexFile.java:296)
		at dalvik.system.DexFile.<init>(DexFile.java:80)
		at dalvik.system.DexFile.<init>(DexFile.java:59)
		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:263)
		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:230)
		at dalvik.system.DexPathList.<init>(DexPathList.java:112)
		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)
		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)
		at android.app.LoadedApk.getClassLoader(LoadedApk.java:326)
		at android.app.LoadedApk.makeApplication(LoadedApk.java:508)
		at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4514)
		... 10 more
```

**Comment by nkartyshov** [comment]
fixed
