### ISSUE TITLE
Unable to start activity ComponentInfo{com.adguard.android.contentblocker/com.adguard.android.contentblocker.MainActivity}: android.view.InflateException: Binary XML file line #10

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#39]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adguard.android.contentblocker/com.adguard.android.contentblocker.MainActivity}: android.view.InflateException: Binary XML file line #10: Error inflating class android.widget.ListView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
	at android.app.ActivityThread.access$600(ActivityThread.java:162)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5400)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #10: Error inflating class android.widget.ListView
	at android.view.LayoutInflater.createView(LayoutInflater.java:613)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:660)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:830)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at com.adguard.android.contentblocker.MainActivity.onCreate(MainActivity.java:75)
	at android.app.Activity.performCreate(Activity.java:5122)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1084)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2336)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
	at android.view.LayoutInflater.createView(LayoutInflater.java:587)
	... 27 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=408; index=104202258
	at android.content.res.TypedArray.getResourceId(TypedArray.java:581)
	at android.widget.ListView.<init>(ListView.java:187)
	at android.widget.ListView.<init>(ListView.java:172)
	... 30 more
```

**Comment by nkartyshov** [comment]
fixed
