### ISSUE TITLE
IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{2685cc9d V.E..... R......D 0,0-667,348} not attached to window manager

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ContentBlocker#40]
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{2685cc9d V.E..... R......D 0,0-667,348} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:402)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:328)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
	at android.app.Dialog.dismissDialog(Dialog.java:431)
	at android.app.Dialog.dismiss(Dialog.java:414)
	at com.adguard.android.contentblocker.ApplyAndRefreshTask.onPostExecute(ApplyAndRefreshTask.java:37)
	at com.adguard.android.contentblocker.ApplyAndRefreshTask.onPostExecute(ApplyAndRefreshTask.java:12)
	at android.os.AsyncTask.finish(AsyncTask.java:632)
	at android.os.AsyncTask.access$600(AsyncTask.java:177)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by nkartyshov** [comment]
fixed
