### ISSUE TITLE
Unable to find explicit activity class {com.yandex.browser.tests/com.yandex.browser.YandexBrowserMainActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/ContentBlocker#42]
```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.yandex.browser.tests/com.yandex.browser.YandexBrowserMainActivity}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1873)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1597)
	at android.app.Activity.startActivityForResult(Activity.java:3745)
	at android.app.Activity.startActivityForResult(Activity.java:3706)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:842)
	at android.app.Activity.startActivity(Activity.java:4016)
	at android.app.Activity.startActivity(Activity.java:3984)
	at com.adguard.android.commons.BrowserUtils.startBrowser(BrowserUtils.java:234)
	at com.adguard.android.commons.BrowserUtils.startYandexBrowser(BrowserUtils.java:219)
	at com.adguard.android.contentblocker.MainActivity$6.onClick(MainActivity.java:197)
	at android.view.View.performClick(View.java:4793)
	at android.view.View$PerformClick.run(View.java:19919)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5499)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
```

**Comment by nkartyshov** [comment]
fixed
