### ISSUE TITLE
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{74fa873 V.E..... R......D 0,0-501,242} not attached to window manager

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/ContentBlocker#43]
```
java.lang.IllegalArgumentException: View=com.android.internal.policy.impl.PhoneWindow$DecorView{74fa873 V.E..... R......D 0,0-501,242} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:412)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:338)
	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:122)
	at android.app.Dialog.dismissDialog(Dialog.java:522)
	at android.app.Dialog$1.run(Dialog.java:128)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6946)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by nkartyshov** [comment]
fixed
