### ISSUE TITLE
SQLiteDatabaseLockedException: database is locked (code 5)

### ISSUE THREAD

**Issue by nkartyshov** [AdguardTeam/ContentBlocker#63]
```
android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:929)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:674)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:356)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:330)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:249)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:227)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:468)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:190)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:182)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:886)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:866)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1293)
	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
	at com.adguard.android.db.FilterListDaoImpl.updateFilterEnabled(FilterListDaoImpl.java:168)
	at com.adguard.android.service.FilterServiceImpl.updateFilterEnabled(FilterServiceImpl.java:163)
	at com.adguard.android.contentblocker.FilterViewAdapter.onClick(FilterViewAdapter.java:111)
	at android.view.View.performClick(View.java:4871)
	at android.view.View$PerformClick.run(View.java:20365)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6102)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by nkartyshov** [comment]
done
